version: '3.1'

services:

  db:
    image: library/postgres:10.7-alpine
    restart: always
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: 9C463B074900
    volumes:
      - ./src/main/resources/db.migration:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

  wiremock:
    build: ./wiremock
    command: --port 7070
    depends_on:
      - db
    ports:
      - "7070:7070"
    volumes:
      - ./wiremock/stubs:/home/wiremock
